FROM hypriot/rpi-golang
RUN apt-get update
RUN mkdir -p /goroot1.5/src/github.com/geodan/gost/
ADD . /goroot1.5/src/github.com/geodan/gost
RUN go get github.com/gorilla/mux
RUN go get gopkg.in/yaml.v2
RUN go get github.com/lib/pq
RUN go get github.com/eclipse/paho.mqtt.golang
RUN go get github.com/gost/now
RUN go build -o /goroot1.5/bin/gost/gost github.com/geodan/gost
RUN cp /goroot1.5/src/github.com/geodan/gost/config.yaml /goroot1.5/bin/gost/config.yaml
WORKDIR /goroot1.5/bin/gost
ENTRYPOINT ["/goroot1.5/bin/gost/gost"]
EXPOSE 8080
